### ISSUE TITLE
watchState not working with vanilla js

### ISSUE THREAD

**Issue by srobertson421** [jbjorge/diffx#3]
Currently testing out the library, looks very cool! Was implementing the count example from the docs and wanted to have a watchState render the new state when it changes. I think I set it up correctly but it doesn't seem to fire the watchState callback when mutating the count property. Here is my code:

```javascript
import { createState, setState, watchState, setDiffxOptions } from 'https://cdn.skypack.dev/@diffx/core';

const countEl = document.querySelector('#counter');
const incButton = document.querySelector('#inc');
const decButton = document.querySelector('#dec');

setDiffxOptions({ createDiffs: true });

const clickState = createState('click state', { count: 0 });

function renderCount(count) {
  countEl.innerText = `Count: ${count}`;
}

const unwatch = watchState(
  () => clickState,
  (newVal, oldVal) => {
    renderCount(newVal.count);
  }
);

incButton.addEventListener('click', () => {
  setState('increase count', () => clickState.count++);
});

decButton.addEventListener('click', () => {
  setState('decrease count', () => clickState.count--);
});
```

**Comment by jbjorge** [comment]
Thanks for the report and clean reproduction! :smiley:

I also get the same error when trying the example you provided, but I can't really see why it happens, and the core tests pass with the same (newest) version of the dependencies as skypack uses.

Could it be skypack doing something weird/non-standard when bundling the code?

Example of a working version here bundled by vite (https://github.com/jbjorge/diffx-core-issue-explorer)

I'll do some investigation during the weekend :+1:

**Comment by srobertson421** [comment]
Ah very possible, I'll attempt with the default node module and see if that works!

**Comment by jbjorge** [comment]
Haven't pinpointed the issue quite yet, but as far as I can tell, the underlying library for Diffx (`@vue/reactivity`) doesn't work when it's compiled with process.env.NODE_ENV = 'production'.
I suspect skypack builds all dependencies in production-mode, so that's out of my control (if that is actually the issue).

To circumvent this, @diffx/core now also offers a browser-importable build as described in https://github.com/jbjorge/diffx/tree/master/core#installation
